// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfpZ4ZhIn-XkKxDvFkBKKPDQ0EM98SCM',
    appId: '1:1080549558559:web:ae420d2ed8e264bc56c82a',
    messagingSenderId: '1080549558559',
    projectId: 'first-apps-85a5b',
    authDomain: 'first-apps-85a5b.firebaseapp.com',
    storageBucket: 'first-apps-85a5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJFPmgsxWdOWFLNFdQ7IJ-0scV3w0PhXw',
    appId: '1:1080549558559:android:e1c254c1aa2d01df56c82a',
    messagingSenderId: '1080549558559',
    projectId: 'first-apps-85a5b',
    storageBucket: 'first-apps-85a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfPm7yvd0NAFf1wMWpN9ChvKQoeAYzrw',
    appId: '1:1080549558559:ios:c8ed24bf5d56bee656c82a',
    messagingSenderId: '1080549558559',
    projectId: 'first-apps-85a5b',
    storageBucket: 'first-apps-85a5b.firebasestorage.app',
    iosBundleId: 'com.example.firstApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOfPm7yvd0NAFf1wMWpN9ChvKQoeAYzrw',
    appId: '1:1080549558559:ios:c8ed24bf5d56bee656c82a',
    messagingSenderId: '1080549558559',
    projectId: 'first-apps-85a5b',
    storageBucket: 'first-apps-85a5b.firebasestorage.app',
    iosBundleId: 'com.example.firstApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfpZ4ZhIn-XkKxDvFkBKKPDQ0EM98SCM',
    appId: '1:1080549558559:web:603308a71747e3b556c82a',
    messagingSenderId: '1080549558559',
    projectId: 'first-apps-85a5b',
    authDomain: 'first-apps-85a5b.firebaseapp.com',
    storageBucket: 'first-apps-85a5b.firebasestorage.app',
  );
}
